### ISSUE TITLE
Why not using just the regular action?

### ISSUE THREAD

**Issue by joaomilho** [markdalgleish/redux-analytics#3]
I would like to understand a little bit more about your use cases and the reasoning why you think it's handful to append more data and a different event type in the meta object.

In my use case I have a fairly complex reporting mechanism to ga's ecommerce thing and receiving the actual event would be enough, since all the data I need to report these events are available in the state. If they are not it seems to me it's easier to do something like:

```
const myAnalyticsStuff = analytics(({type}, state) => {
  switch(type){
  case SOME_REGULAR_ACTION:
    ... some complex ga report based on type and current state ...
    break;
  }
});
```

(Unfortunately JS doesn't have guards :/)

What do you say?

**Comment by markdalgleish** [comment]
We found out useful to be able to easily flag an action to be tracked, with a curated subset of the action's payload. Obviously that doesn't fit more advanced usage patterns, but this library is designed for use with simple event based tracking tools. We've ended up using it more for metrics than analytics, actually.
